[server]
headless = true
port = 8501
address = "0.0.0.0"
baseUrlPath = ""
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 200
maxMessageSize = 200
enableWebsocketCompression = false

[logger]
level = "info"

[theme]
base = "dark"
primaryColor = "#c62e3f"
backgroundColor = "#060606"
secondaryBackgroundColor = "#111114"
textColor = "#f6f1f2"
